# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1246, 714)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_pages = QtWidgets.QFrame(self.centralwidget)
        self.frame_pages.setGeometry(QtCore.QRect(100, 0, 1141, 711))
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_pages)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_pages)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_main = QtWidgets.QWidget()
        self.page_main.setObjectName("page_main")
        self.label_1 = QtWidgets.QLabel(self.page_main)
        self.label_1.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.label_1.setObjectName("label_1")
        self.stackedWidget.addWidget(self.page_main)
        self.page_cameras = QtWidgets.QWidget()
        self.page_cameras.setObjectName("page_cameras")
        self.label_2 = QtWidgets.QLabel(self.page_cameras)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page_cameras)
        self.page_settings = QtWidgets.QWidget()
        self.page_settings.setObjectName("page_settings")
        self.label = QtWidgets.QLabel(self.page_settings)
        self.label.setGeometry(QtCore.QRect(10, 0, 61, 16))
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page_settings)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.frame_menu = QtWidgets.QFrame(self.centralwidget)
        self.frame_menu.setGeometry(QtCore.QRect(0, 0, 100, 720))
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.btn_main = QtWidgets.QPushButton(self.frame_menu)
        self.btn_main.setGeometry(QtCore.QRect(10, 10, 80, 80))
        self.btn_main.setObjectName("btn_main")
        self.btn_cameras = QtWidgets.QPushButton(self.frame_menu)
        self.btn_cameras.setGeometry(QtCore.QRect(10, 100, 80, 80))
        self.btn_cameras.setObjectName("btn_cameras")
        self.btn_settings = QtWidgets.QPushButton(self.frame_menu)
        self.btn_settings.setGeometry(QtCore.QRect(10, 190, 80, 80))
        self.btn_settings.setObjectName("btn_settings")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_1.setText(_translate("MainWindow", "Main"))
        self.label_2.setText(_translate("MainWindow", "Camera\'s"))
        self.label.setText(_translate("MainWindow", "Settings"))
        self.btn_main.setText(_translate("MainWindow", "Main"))
        self.btn_cameras.setText(_translate("MainWindow", "Camera\'s"))
        self.btn_settings.setText(_translate("MainWindow", "Settings"))
